apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: MTAuMTY3LjAuMw==     
  DB_PORT: NTQzMg==            
  DB_NAME: Y2hhdGJvdF9kYg==             
  DB_USER: Y2hhdGJvdF9hcHA=
  DB_PASSWORD: RFJrU1FKQ1lEbVZPNGEoWg==        
  #if you create new instacne, you need to change this value
  INSTANCE_CONNECTION_NAME: dHVybmtleS1ndWlsZC00NDExMDQtZjM6dXMtY2VudHJhbDE6Y2hhdGJvdC1wb3N0Z3Jlcw==